name: Comment E2E Summary
on:
  workflow_call:

jobs:
  comment:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node scripts/pr-comment-e2e.js > e2e-comment.md
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: e2e-test-summary
          path: e2e-comment.md
