name: Deploy Preview to Firebase
on:
  workflow_call:
    secrets:
      FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_MIKEPAWLAK: {}
      GITHUB_TOKEN: {}

jobs:
  deploy:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm ci --prefix apps/functions && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_MIKEPAWLAK }}
          projectId: portfolio-mikepawlak
          channelId: pr-${{ github.event.pull_request.number }}
