name: "Lint Project"
description: "Run linter checks"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run linter
      run: npm run lint
      shell: bash
