name: "Deploy Production"
description: "Deploy to Firebase Hosting and Cloud Functions"

runs:
  using: "composite"
  steps:
    - name: Inject secrets into environment.prod.ts
      run: |
        echo "export const environment = {
          production: true,
          firebase: {
            apiKey: '${{ env.FIREBASE_API_KEY }}',
            authDomain: '${{ env.FIREBASE_AUTH_DOMAIN }}',
            projectId: 'portfolio-mikepawlak',
            storageBucket: '${{ env.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ env.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ env.FIREBASE_APP_ID }}',
            measurementId: '${{ env.FIREBASE_MEASUREMENT_ID }}'
          },
          useEmulator: false
        };" > apps/web/src/environments/environment.prod.ts
      shell: bash

    - name: Deploy hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ env.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ env.FIREBASE_SERVICE_ACCOUNT }}
        channelId: live
        projectId: portfolio-mikepawlak

    - name: Deploy functions
      uses: joinflux/firebase-tools@v14.6.0
      with:
        args: deploy --only functions --project portfolio-mikepawlak
      env:
        GCP_SA_KEY: ${{ env.GCP_SA_KEY }}
