name: "Deploy Prod"
description: "Deploy to Firebase Hosting and Functions"
inputs:
  firebase_service_account:
    required: true
  gcp_sa_key:
    required: true
runs:
  using: "composite"
  steps:
    - name: Inject production environment
      run: |
        echo "export const environment = {
          production: true,
          firebase: {
            apiKey: '${{ env.FIREBASE_API_KEY }}',
            authDomain: '${{ env.FIREBASE_AUTH_DOMAIN }}',
            projectId: 'portfolio-mikepawlak',
            storageBucket: '${{ env.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ env.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ env.FIREBASE_APP_ID }}',
            measurementId: '${{ env.FIREBASE_MEASUREMENT_ID }}'
          },
          useEmulator: false
        };" > apps/web/src/environments/environment.prod.ts
      shell: bash

    - name: Deploy Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ env.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ inputs.firebase_service_account }}
        projectId: portfolio-mikepawlak
        channelId: live

    - name: Deploy Functions
      uses: joinflux/firebase-tools@v14.6.0
      with:
        args: deploy --only functions --project portfolio-mikepawlak
      env:
        GCP_SA_KEY: ${{ inputs.gcp_sa_key }}
