name: "Run E2E Tests"
description: "Run Playwright E2E tests against built app"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: Install dependencies
      run: npm ci && npx playwright install --with-deps
      shell: bash

    - name: Start Firestore Emulator
      run: |
        set -e
        npm install -g firebase-tools
        npm install --prefix apps/functions
        npm run build --prefix apps/functions

        echo "Starting backend emulator..."
        firebase emulators:start --only firestore,functions --project portfolio-mikepawlak --config firebase.json > emulators.log 2>&1 &
        echo "Waiting for Firestore emulator..."
        sleep 15
      shell: bash

    - name: Serve UI
      run: |
        npm run start:ui:ci &
        npx wait-on http://localhost:4200
      shell: bash

    - name: Run E2E tests
      run: npm run e2e
      shell: bash
