name: "Deploy Preview"
description: "Deploy preview site to Firebase Hosting"
inputs:
  pr_number:
    required: true
  firebase_service_account:
    required: true
runs:
  using: "composite"
  steps:
    - name: Firebase Preview Deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ env.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ inputs.firebase_service_account }}
        projectId: portfolio-mikepawlak
        channelId: pr-${{ inputs.pr_number }}
