name: "Deploy to Firebase Preview"
description: "Deploy preview site to Firebase for PR"

inputs:
  pr_number:
    required: true
    description: "PR number for preview channel"

runs:
  using: "composite"
  steps:
    - name: Deploy preview to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ env.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ env.FIREBASE_SERVICE_ACCOUNT }}
        projectId: portfolio-mikepawlak
        channelId: pr-${{ inputs.pr_number }}
