name: Deploy to Firebase Hosting on merge
on:
  workflow_run:
    workflows:
      - E2E Tests
    types:
      - completed 
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm ci  --prefix apps/functions && npm run build
      - name: Inject secrets into environment.prod.ts
        run: |
          echo "export const environment = {
            production: true,
            firebase: {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
              projectId: 'portfolio-mikepawlak',
              storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}',
              measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
            },
            useEmulator: false
          };" > apps/web/src/environments/environment.prod.ts
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_MIKEPAWLAK }}
          channelId: live
          projectId: portfolio-mikepawlak
      - name: Deploy Cloud Functions
        uses: joinflux/firebase-tools@v14.6.0
        with:
          args: deploy --only functions --project portfolio-mikepawlak
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}