name: CI on Merge to Main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: ./.github/actions/lint

  unit_tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: ./.github/actions/test

  e2e_tests:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - uses: ./.github/actions/e2e

  deploy_prod:
    runs-on: ubuntu-latest
    needs: e2e_tests
    steps:
      - uses: ./.github/actions/deploy_prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_MIKEPAWLAK }}
